
package com.blog.samples.webservices.accountservice;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "AccountDetailsServices", targetNamespace = "http://com/blog/samples/webservices/accountservice", wsdlLocation = "file:/D:/NEW_DEMO/webservice/src/main/resources/wsdl/AccountDetailsService.wsdl")
public class AccountDetailsServices
    extends Service
{

    private final static URL ACCOUNTDETAILSSERVICES_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.blog.samples.webservices.accountservice.AccountDetailsServices.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.blog.samples.webservices.accountservice.AccountDetailsServices.class.getResource(".");
            url = new URL(baseUrl, "file:/D:/NEW_DEMO/webservice/src/main/resources/wsdl/AccountDetailsService.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/D:/NEW_DEMO/webservice/src/main/resources/wsdl/AccountDetailsService.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        ACCOUNTDETAILSSERVICES_WSDL_LOCATION = url;
    }

    public AccountDetailsServices(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AccountDetailsServices() {
        super(ACCOUNTDETAILSSERVICES_WSDL_LOCATION, new QName("http://com/blog/samples/webservices/accountservice", "AccountDetailsServices"));
    }

    /**
     * 
     * @return
     *     returns AccountDetailsService
     */
    @WebEndpoint(name = "AccountDetailsServiceSoap11")
    public AccountDetailsService getAccountDetailsServiceSoap11() {
        return super.getPort(new QName("http://com/blog/samples/webservices/accountservice", "AccountDetailsServiceSoap11"), AccountDetailsService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AccountDetailsService
     */
    @WebEndpoint(name = "AccountDetailsServiceSoap11")
    public AccountDetailsService getAccountDetailsServiceSoap11(WebServiceFeature... features) {
        return super.getPort(new QName("http://com/blog/samples/webservices/accountservice", "AccountDetailsServiceSoap11"), AccountDetailsService.class, features);
    }

}
