
package com.blog.samples.webservices.accountservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "AccountDetailsService", targetNamespace = "http://com/blog/samples/webservices/accountservice")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    com.blog.samples.webservices.ObjectFactory.class,
    com.blog.samples.webservices.accountservice.ObjectFactory.class
})
public interface AccountDetailsService {


    /**
     * 
     * @param accountDetailsRequest
     * @return
     *     returns com.blog.samples.webservices.accountservice.AccountDetailsResponse
     */
    @WebMethod(operationName = "AccountDetails")
    @WebResult(name = "AccountDetailsResponse", targetNamespace = "http://com/blog/samples/webservices/accountservice", partName = "AccountDetailsResponse")
    public AccountDetailsResponse accountDetails(
        @WebParam(name = "AccountDetailsRequest", targetNamespace = "http://com/blog/samples/webservices/accountservice", partName = "AccountDetailsRequest")
        AccountDetailsRequest accountDetailsRequest);

}
